In [2]:
import numpy as np
import pandas as pd



In [3]:
df=pd.read_csv("/content/drive/MyDrive/dataset/house predict.csv")
df.head()
x=df.iloc[:,:-1].values
y=df.iloc[:, 11].values
print(x.shape)
print(y.shape)

(29451, 11)
(29451,)


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   POSTED_BY              29451 non-null  object 
 1   UNDER_CONSTRUCTION     29451 non-null  int64  
 2   RERA                   29451 non-null  int64  
 3   BHK_NO.                29451 non-null  int64  
 4   BHK_OR_RK              29451 non-null  object 
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64  
 7   RESALE                 29451 non-null  int64  
 8   ADDRESS                29451 non-null  object 
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), object(3)
memory usage: 2.7+ MB


In [5]:
df.describe()

UNDER_CONSTRUCTION          RERA       BHK_NO.     SQUARE_FT  \
count        29451.000000  29451.000000  29451.000000  2.945100e+04   
mean             0.179756      0.317918      2.392279  1.980217e+04   
std              0.383991      0.465675      0.879091  1.901335e+06   
min              0.000000      0.000000      1.000000  3.000000e+00   
25%              0.000000      0.000000      2.000000  9.000211e+02   
50%              0.000000      0.000000      2.000000  1.175057e+03   
75%              0.000000      1.000000      3.000000  1.550688e+03   
max              1.000000      1.000000     20.000000  2.545455e+08   

       READY_TO_MOVE        RESALE     LONGITUDE      LATITUDE  \
count   29451.000000  29451.000000  29451.000000  29451.000000   
mean        0.820244      0.929578     21.300255     76.837695   
std         0.383991      0.255861      6.205306     10.557747   
min         0.000000      0.000000    -37.713008   -121.761248   
25%         1.000000      1.000000     18.452663     73.798100   
50%         1.000000      1.000000     20.750000     77.324137   
75%         1.000000      1.000000     26.900926     77.828740   
max         1.000000      1.000000     59.912884    152.962676   

       TARGET(PRICE_IN_LACS)  
count           29451.000000  
mean              142.898746  
std               656.880713  
min                 0.250000  
25%                38.000000  
50%                62.000000  
75%               100.000000  
max             30000.000000

In [6]:
import pandas as pd
pd.isnull(df)

POSTED_BY  UNDER_CONSTRUCTION   RERA  BHK_NO.  BHK_OR_RK  SQUARE_FT  \
0          False               False  False    False      False      False   
1          False               False  False    False      False      False   
2          False               False  False    False      False      False   
3          False               False  False    False      False      False   
4          False               False  False    False      False      False   
...          ...                 ...    ...      ...        ...        ...   
29446      False               False  False    False      False      False   
29447      False               False  False    False      False      False   
29448      False               False  False    False      False      False   
29449      False               False  False    False      False      False   
29450      False               False  False    False      False      False   

       READY_TO_MOVE  RESALE  ADDRESS  LONGITUDE  LATITUDE  \
0              False   False    False      False     False   
1              False   False    False      False     False   
2              False   False    False      False     False   
3              False   False    False      False     False   
4              False   False    False      False     False   
...              ...     ...      ...        ...       ...   
29446          False   False    False      False     False   
29447          False   False    False      False     False   
29448          False   False    False      False     False   
29449          False   False    False      False     False   
29450          False   False    False      False     False   

       TARGET(PRICE_IN_LACS)  
0                      False  
1                      False  
2                      False  
3                      False  
4                      False  
...                      ...  
29446                  False  
29447                  False  
29448                  False  
29449                  False  
29450                  False  

[29451 rows x 12 columns]

In [7]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder 
labelencoder_x=LabelEncoder()
x[:,0]=labelencoder_x.fit_transform(x[:,0])
x[:,8]=labelencoder_x.fit_transform(x[:,8])
x[:,4]=labelencoder_x.fit_transform(x[:,4])
print(x)

[[2 0 0 ... 2844 12.96991 77.59796]
 [1 0 0 ... 6576 12.274538 76.644605]
 [2 0 0 ... 2256 12.778033 77.632191]
 ...
 [1 0 0 ... 150 26.928785 75.828002]
 [2 0 0 ... 5707 12.90015 80.22791]
 [1 0 1 ... 2154 26.832353 75.841749]]


In [8]:
print(x[:,8])

[2844 6576 2256 ... 150 5707 2154]


In [9]:
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
print(y)

[494 455 372 ... 210 615 217]


In [10]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
print(sc_x)
x_sc=sc_x.fit_transform(x)
x_sc

StandardScaler()


array([[ 1.28713168, -0.46813431, -0.68271456, ..., -0.35227112,
        -1.34247787,  0.07201136],
       [-0.65335028, -0.46813431, -0.68271456, ...,  1.52426846,
        -1.45454064, -0.01828927],
       [ 1.28713168, -0.46813431, -0.68271456, ..., -0.64793169,
        -1.37339983,  0.07525368],
       ...,
       [-0.65335028, -0.46813431, -0.68271456, ..., -1.70687927,
         0.90706647, -0.09563692],
       [ 1.28713168, -0.46813431, -0.68271456, ...,  1.08731431,
        -1.35372005,  0.32111704],
       [-0.65335028, -0.46813431,  1.464741  , ..., -0.69921975,
         0.89152595, -0.09433482]])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_sc,y,test_size=0.2,random_state=0)
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
x_train
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[-0.65685352 -0.46860212  1.46390218 ...  1.54443266  0.53935628
   0.15091595]
 [-0.65685352  2.13400655  1.46390218 ... -1.34227264 -1.32567406
   0.08084612]
 [-0.65685352  2.13400655  1.46390218 ... -1.26035535  0.53935628
   0.15091595]
 ...
 [ 1.28194239 -0.46860212 -0.68310575 ...  1.45045391  0.15447533
  -0.3467645 ]
 [ 1.28194239 -0.46860212  1.46390218 ...  0.95945268  1.16081834
   0.05348392]
 [-0.65685352  2.13400655  1.46390218 ...  0.82627425  1.13869665
   0.06275777]]
[[  1.28194239  -0.46860212  -0.68310575 ...   1.17103049   3.25121018
  -15.45823673]
 [  1.28194239  -0.46860212  -0.68310575 ...   0.44231832   0.89367857
   -0.09770124]
 [  1.28194239  -0.46860212  -0.68310575 ...   1.1318308   -0.62111565
    0.15854577]
 ...
 [  1.28194239  -0.46860212  -0.68310575 ...   0.64233725   0.39996559
    0.90669842]
 [  1.28194239   2.13400655  -0.68310575 ...   0.40713912  -1.14744336
    0.09372887]
 [ -0.65685352  -0.46860212  -0.68310575 ...   0.76998752   1.133048

In [12]:
# Fitting Simple Regression to training set
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [13]:
regressor.coef_

array([-8.95928896e+01, -3.60992187e+14,  3.14843750e+01,  1.33496094e+02,
       -1.41601562e+00,  4.77294922e+00, -3.60992187e+14,  2.25937500e+01,
        2.44531250e+00, -6.25195312e+01, -2.99199219e+01])

In [14]:
regressor.intercept_

580.6420127029282

In [15]:
y_pred = regressor.predict(x_test)
print(y_pred) 

print(y_test)

[808.09439726 343.83696722 432.56037468 ... 495.42247081 290.44585581
 649.25361082]
[922 306 744 ... 259  87 620]


In [16]:
regressor.score(x_test,y_test)

0.34714177368754984

In [17]:
from sklearn.metrics import mean_absolute_error
mae=mean_absolute_error(y_test,y_pred)
print(mae)

198.89212980828881


In [18]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)

56325.39089381978
